### ISSUE TITLE
Some fields in trigger cards in AYCT-202 remote are showing labels instead of strings

### ISSUE THREAD

**Issue by rhannink** [athombv/nl.klikaanklikuit#11]
![flow_-_homey](https://cloud.githubusercontent.com/assets/1661824/22152396/0f5131d8-df23-11e6-8b86-586928902ae8.png)

**Comment by BasKiers** [comment]
Hi, 

Thank you for reporting this issue. This should be fixed as of version 3.0.1

Regards, 
Bas
