### ISSUE TITLE
awst-8802 wall switch will crash homey

### ISSUE THREAD

**Issue by AlbertDijksma** [athombv/nl.klikaanklikuit#14]
Hi Athom,

When I use the awst-8802 wall switch to activate a flow which is switch some kaku apa3-1500r the home kaku will crass some times.
I need to reboot homey to get it working again.

My home firmware is: 1.1.4
My kaku version is: 3.0.0

**Comment by BasKiers** [comment]
Hi, 

I am unable to reproduce the issue. Could you provide more information of your issue? For instance, does the KaKu app crash (you can see this in the settings->apps page) and if so what does the error say. If this is not the case could you try pressing the "reset microcontroller" button in settings->system->stuff for geeks->restart microcontroller and check if this fixes the issue.

Could you also generate a log after this happens (before rebooting Homey) and post the log id here by going to settings->system->send log.

Regards,
Bas

**Comment by AlbertDijksma** [comment]
Hi Bas,

I have retested (reused) my kaku awst-8802 switch.
Everything is working perfect now.
I don’t understand why it is working now.
Maybe there is something fixed between version 1.1.4 and 1.1.9 or kaku version 3.00 and 3.01?

Kind regards
Albert
