### ISSUE TITLE
suggestion: separate doorbell and its button for ACDB-7000* devices

### ISSUE THREAD

**Issue by gratjetost** [athombv/nl.klikaanklikuit#17]
I would like to suggest to separate the ACDB-7000A and B (the buttons) from the ACDB-7000C and ACDB-6600 (the doorbells).
now you always see the same icon for both devices. but you can buy the buttons and the doorbells separately.

**Comment by Dijker** [comment]
The answer is already here: https://github.com/athombv/homey/issues/663

**Comment by jeroenvollenbrock** [comment]
Closed as duplicate
