### ISSUE TITLE
Flow triggers twice

### ISSUE THREAD

**Issue by mwajansen** [athombv/nl.klikaanklikuit#2]
Using remote AYCT-102 to trigger a flow. It will trigger twice.
To test this set homey to say something when triggered. It will always say it twice.

**Comment by BasKiers** [comment]
Hi,

I increased the debounce timeout from 300 milliseconds to 500 milliseconds as of v2.9.0. Could you check if this fixed your issue?

Regards,
Bas

**Comment by BasKiers** [comment]
Hi, 

I've fixed another bug which would prevent flows triggering multiple times in some instances in version 3.0.1 of the app. 

Regards,
Bas

**Comment by dolfje** [comment]
Hey, I still have issues with flows triggering twice
