### ISSUE TITLE
AWMR-230 not responding on Flows

### ISSUE THREAD

**Issue by pimviergever** [athombv/nl.klikaanklikuit#20]
Homey Firmware Versie: 1.3.0-rc.7
KlikAanKlikUit v3.1.1

AWMR-230 is correctly recognized, and added as device. When switching the AWMR-230 is switched on /off  using:
- the hardware switch
- the IOS app on iPhone
- the Homey webinterface using Chrome.
- when testing a flow where the AWMR-230 is used in the 'Then' colomn
The  AWMR-230 is working correctly!

But when the flow is activated and triggered, all devices in the Then colomn are responding except the AWMR-230.
The flow has been deleted and a new flow was created: same result
Reboot of homey did not  fix the problem
Re-adding the AWMR-230 did not fix the problem.

Log dump: ED32DF1B09

Please let the AWMR-230 be used correctly when used in flows

![afbeelding](https://cloud.githubusercontent.com/assets/10696231/26447542/3da86244-4149-11e7-8d16-476c62e92a6e.png)

**Comment by pimviergever** [comment]
@Homey 1.3.2
@KaKu 3.1.5 

the problem still persists, the AWMR-230 is working when controlled without a flow. When it's controlled within a flow, it doesn not work.

Homey log: EC7EAA9030

**Comment by BasKiers** [comment]
Hi, 

could you check if it does work when you add a small delay to the action card, for instance 2 seconds? Some users have reported that this fixes the problems they were having in similar situations. We are still looking for the cause of this bug.

Regards,
Bas

**Comment by pimviergever** [comment]
yep! 2 seconds did the trick! i'll start editing the other flows as well. this seems to work for now

**Comment by BasKiers** [comment]
I've created an internal issue for this problem since it has to do with the microcontroller of Homey
