### ISSUE TITLE
KAKU not working after 1.3.1 and 1.3.2 updates

### ISSUE THREAD

**Issue by rhannink** [athombv/nl.klikaanklikuit#21]
Most of my receivers are not working anymore after todays updates.......

**Comment by jjtbsomhorst** [comment]
Same here. For me only 2 out of 5 devices still respond. The devices that do not respond anymore are: 
2 ACM-1000
1 APA3-1500

The devices that do work are 
1 APA3-1500
1 ACM-1000 

so it seems to be completely random? Maybe the signals are 'lost'? I added them using a generated custom signal by homey

**Comment by AlbertDijksma** [comment]
Same here
Only 3 out of 4 devices respond in one flow.
The last one in the flow is not respondig

**Comment by BasKiers** [comment]
Hi,

Could you confirm that this issue still persists?

Regards,
Bas

**Comment by rhannink** [comment]
Bas,

I am on firmware version 1.5.3 at this moment and all my KAKU switches work fine. 

Gr. Remco

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
