### ISSUE TITLE
Device ACM-3000H2 add

### ISSUE THREAD

**Issue by roeltjeeh** [athombv/nl.klikaanklikuit#25]
Is it possible to add the ACM-3000H2.
Thankyou!

**Comment by BasKiers** [comment]
Hi,

Unfortunately, for now, we do not add kaku devices that connect to multiple devices. However, you can still add your ACM-3000H2 by pairing both sides as a separate ACM-1000 device.

Regards,
Bas

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2649
