### ISSUE TITLE
AWST-6000 & APIR-2150 Problems

### ISSUE THREAD

**Issue by Pauweltje** [athombv/nl.klikaanklikuit#26]
Hi All,

Both the KAKU sensors: AWST-6000 and APIR-2150, on or of state, doesn't trigger any Homey actions!

For instance, when someone triggers a sensor, I want some of my Hue lights to blink, and I want homey to say something.

When I run the flow manualy, it all works fine, but it looks like Homey doesn't process the 433 Mhz on/off signal of the sensors correctly.

I use Kaku app version v3.1.5 - 22.06.17 / Homey Firmware Versie: 1.3.1

I realy want this to work, please fix this...

Regards,
Hack

**Comment by lubbertkramer** [comment]
Maybe good to edit your post wich Kaku version of the app you use and if you are on stable 1.3 or experimental 1.5

**Comment by HackAzz** [comment]
Done...edited! ;-)

**Comment by rtnartna** [comment]
Same issue?

https://github.com/athombv/nl.klikaanklikuit/issues/21

**Comment by HackAzz** [comment]
@rtnartna yep

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by HackAzz** [comment]
Jammer dat hier wel gekeken wordt, maar er geen oplossing of hulp wordt geboden...

**Comment by elwin23** [comment]
None of my kaku devices are working anymore, all of them working fine before for a while.
apa3-1500r remote, 2x apa3-1500r plug and a awst-8802, using 3.1.5 kaku app and homey 1.3.1 firmware. Other stuff like z-wave, hue and ring working fine. could the unit be broken or simular issue as people above? Tried reboot (hard), reinstall kaku app, and now I can't pair any of them.

**Comment by jjtbsomhorst** [comment]
@jeroenvollenbrock or @WeeJeWel  please look into this issue? I just bought myself a AWST-6000 and pairing the device is no problem but using it is a complete different story. It doesn't react at all.

**Comment by HackAzz** [comment]
I think I am going to swap the kaku for zigbee or z-wave devices. Kaku is not reliable enough.

**Comment by HackAzz** [comment]
Niemand helpt zoals altijd!

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2648

**Comment by Pauweltje** [comment]
All the Kaku’s has left the building period!
