### ISSUE TITLE
Par-1000 not working anymore

### ISSUE THREAD

**Issue by rhannink** [athombv/nl.klikaanklikuit#28]
I try to add som KlikAanKlikUit par-1000 sockets to Homey. The codes are set to b3 or C2 and I add a device to Homey. I enter the fixed code but the socket does not respond. I tried 2 different sockets and different codes but it does’t work.

**Comment by BasKiers** [comment]
Hi,

Could you try setting a socket to A1 and try to pair it to Homey?

Regards,
Bas

**Comment by rhannink** [comment]
Just tried a PA-R-1000

A1 -> working ok
A2 -> not working
D2 -> not working

Gr. Remco

**Comment by BasKiers** [comment]
Hi,

I am currently completing a rewrite to SDK2 which I am planning to release on the beta channel of the KlikAanKlikUit app soon. This will be version 4.0.0.

This version should fix the bug you described.

Regards,
Bas

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2647
