### ISSUE TITLE
Please add support for SAFY / Rolertrol / Hasta new protocol

### ISSUE THREAD

**Issue by snillevilla** [athombv/nl.klikaanklikuit#29]
Could you please add support for Rolertrol roller blinds? The specific device I am interested in is this motor:
https://www.m.nu/rullgardin/tubmotor-12v-for-20mm-ror (BOFU)
I can provide you with logs from RfxTrx and pyRFXtrx (https://github.com/Danielhiversen/pyRFXtrx).
Alternatively, point me in the right direction, maybe I can add the support myself if it is not too complicated?

**Comment by BasKiers** [comment]
Hi,

I came across your issue while updating the klikaanklikuit app and looking at your picture it seems the motor is made by BOFU. We made an app in collaboration with sunway who also use BOFU motors so you could try installing the sunway app and pairing your blinds with the BOFU remote device in that app.

Regards,
Bas
