### ISSUE TITLE
ALMDT-2000 not supported

### ISSUE THREAD

**Issue by Zwoops** [athombv/nl.klikaanklikuit#3]
Please add support for the ALMDT-2000, it's a 868mhz PIR motion sensor by klikaanklikuit.

Thanks.

**Comment by MarkLeemans** [comment]
I would like this too, they're for sale at the Albert Heijn now. I bought a couple of KaKu 868Mhz Devices for 7,5 euro's each!

**Comment by BasKiers** [comment]
Hi,

Support for 868 devices in athom apps will be coming in the near future. Since KlikAanKlikUit is one of our biggest apps I will look into supporting this device as well as other kaku 868 devices when I start implementing 868 devices. 

Regards,
Bas

**Comment by MarkLeemans** [comment]
Hi Bas, are there any updates?

**Comment by fu33ybear** [comment]
Hi Any update on the implementation of the ALMDT-2000 Plus line

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2656
