### ISSUE TITLE
[ASUN-650] Add device class

### ISSUE THREAD

**Issue by mettin** [athombv/nl.klikaanklikuit#30]
When adding an ASUN-650 the user should get the option to select which type of device is hooked up to it. That way voice commands will work a lot better. Now when i say: 'close the curtains downstairs' my sunshades downstairs also responds.

Proposed solution: after succesfully linking an ASUN 650 device the user should get an option to select this, just like when adding a KAKU socket thingy.

**Comment by mettin** [comment]
Hey guys, any update?

**Comment by WeeJeWel** [comment]
Yes, this is planned for Homey v2.0.0

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2646
