### ISSUE TITLE
AGD2-3500R remote badly responding

### ISSUE THREAD

**Issue by Alxwin** [athombv/nl.klikaanklikuit#33]
Just bought a set with to Kaku plugs for outside and a remote. Got the plugs working perfectly. The remote wasn't in the devices supported list, but I got it working by adding it as AYCT-102. The buttons are the same as the remote I have. After succesfully adding it to homey and adding it as trigger for a flow it  unfortunately reacts to remote inputs very badly. Tried adding it again, rebooting homey and adding it as another remote type. Without any effect. Any suggestions to solve this? Thanks in advance!

**Comment by Alxwin** [comment]
Forgot to add the firmware. Homey firmware 1.5.8 and Kaku 3.1.5

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2644
