### ISSUE TITLE
KlikAanKlikUit cannot start after updating to 4.0.0 beta from 3.1.5 stable

### ISSUE THREAD

**Issue by pellz0r** [athombv/nl.klikaanklikuit#35]
KlikAanKlikUit beta doesn't start at all on the Homey since I upgraded to the beta. I've tried restarting both the app and Homey, but to no avail. I did click on the link to send a crash report.

**Comment by sintav1325** [comment]
I have the same issue. Is there a work around of solution?

**Comment by WoutervdBrink** [comment]
Hi there, thank you for your bug report. I have published a fix as a beta in the app store. Could you please install it when it becomes available and let me know if the issue persists?

Also, sorry for closing this issue; the commit message of my fix contained "fix #35", letting GitHub assume I wanted to close this issue :wink:.

**Comment by pellz0r** [comment]
Just installed the beta version (4.0.1) which had todays date, and it seem to be working fine! :)

**Comment by WoutervdBrink** [comment]
Cool, thanks for your feedback! I will close this issue now.
