### ISSUE TITLE
Support for ALSIR-2000

### ISSUE THREAD

**Issue by pmolensky** [athombv/nl.klikaanklikuit#37]
Is it possible to add support for the ALSIR-2000 siren?
![image](https://user-images.githubusercontent.com/29775347/42006240-f5091668-7a78-11e8-9b55-90d628ac57bb.png)

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
