### ISSUE TITLE
AKCT-510 not pairable

### ISSUE THREAD

**Issue by rickerd** [athombv/nl.klikaanklikuit#39]
I bought a new KAKU KCT-510 keychain remote (and got send a COCO AKCT-510)
Tried to pair but i gave error at the first try. Resetting en restarting Homey didn't work at all.

![schermafbeelding 2018-09-01 om 13 36 08](https://user-images.githubusercontent.com/1032429/44945562-7153bb00-adec-11e8-80a7-6f429130811f.png)

**Comment by KyleAthom** [comment]
Hi @rickerd ,

Thank you for reporting your issue. Currently the App repository issue trackers are not being monitored, all (App related) issues should be reported at https://github.com/athombv/homey/issues. Due to this change I have moved your issue to: https://github.com/athombv/homey/issues/2802

**Comment by rickerd** [comment]
Thanks and sorry!

My way of working is via GitHub since the code lives there.
Pull requests can be closed and stuff there.

Thanks for moving the issue.
