### ISSUE TITLE
No "and-type" flow cart for "Is turned off"

### ISSUE THREAD

**Issue by acekrystal** [athombv/nl.klikaanklikuit#4]
When building flows with a kaku on/off switch there is a flow cart for saying ...and..."Is turned on", but there is non for saying ...and..."Is turned off".

UseCase : I want the flow to turn all the other lights off in a room if an other light was already off. (to check my intention/presence).

I tried searching on "Is turned on" in the code but couldn't find anything, so I'm not sure if this request is in the proper place.

**Comment by WeeJeWel** [comment]
Press the checkbox in the upper right corner, the text will change to 'is turned off' ;-)

**Comment by acekrystal** [comment]
Thats the problem, that isn't working for me. The box is there as I expected, but pressing it doesn't do/change the cart/text to "off". And the box itself also doesn't get checked.

So I expected what you described, but it seems it doesn't do that. ;)

**Comment by acekrystal** [comment]
Wow, that is strange, somehow it does work now.. I checked it again.
I'm using Chrome browser, 26-12 evening and 27-12 morning I tested the thoroughly (multiple try's in different flows with different switches. other devices seemed to check the "invert" box just fine, but all the kaku switches didn't do that only in the "...and..." column. Restart Chrome did not fix it. Pressing checkbox made the "pressed-down" animation while holding it down, but releasing did not change anything.

I tested it now again, and now it does the same thing, but only for the first time after dragging the cart in. the second try now does check the box and make it all work as expected. Throwing the cart away and dragging it in again repeats again the problem of not getting "checked" after the first click, but it does work the 2nd click again.

So I don't know what the problem earlier, but it seems to work okay for now (except for the that you need to press 2 times the first time. But all the carts with a "invert" check box seem to do this.)
