### ISSUE TITLE
Cannot add APA3-1500R with generated code

### ISSUE THREAD

**Issue by DIYglenn** [athombv/nl.klikaanklikuit#44]
I have a few NEXA devices (PER-1500 and PET-910) which are similar to APA3-1500R.
While I can add APA3-1500R using cloning from APA3-1500R remote, I cannot add them directly with a generated code, even though I reset them (with group off on the remote), they never responds with a new signal from Homey.

Adding from cloning the remote works perfectly, but then I cannot use the remote for other functions.

Is it a bug or a missing support in the APA3-1500R?

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
