### ISSUE TITLE
Support for ACM-2300H

### ISSUE THREAD

**Issue by kslinger** [athombv/nl.klikaanklikuit#6]
Can support for the ACM-2300H please be added?
Advantage of the ACM-2300H is that it can easily be used in combination with a traditional wall switch.
Thanks in advance

**Comment by BasKiers** [comment]
Hi, 

I am planning to add more devices to the app in the near future. I added this device to the todo list, thanks for the input!

Regards,
Bas

**Comment by BasKiers** [comment]
Hi,

I just updated the app to include the AYCT-202. You can sideload the app from this repository or wait until I update the app in the appstore next week.

Regards,
Bas
