### ISSUE TITLE
Support for ayct-202

### ISSUE THREAD

**Issue by rhannink** [athombv/nl.klikaanklikuit#7]
KlikaanKlikuit has a new remote control switch, AYCT-202 specially for dimmers and dimmable lights. 
On/off buttons, more/less brightness and select channel (1-4) button.

**Comment by BasKiers** [comment]
Hi, 

I just updated the app to include the AYCT-202. You can sideload the app from this repository or wait until I update the app in the appstore next week.

Regards, 
Bas
