### ISSUE TITLE
Support for ACDB-7000B

### ISSUE THREAD

**Issue by hunter707** [athombv/nl.klikaanklikuit#8]
Is it possible to ad support for the doorbell button ACDB-7000B?
![schermafbeelding 2017-01-15 om 00 14 35](https://cloud.githubusercontent.com/assets/25126272/21958961/f351e904-dab9-11e6-9a55-a91a6fdf0b32.png)

**Comment by BasKiers** [comment]
Hi,

The ACDB-7000B is supported in the KlikAanKlikUit app. This device does not have a seperate driver for the doorbell and the alarm but the functionality is combined to avoid having 2x the amount of doorbell devices and potentially confusing users. You can add this device as an ACDB-7000C and only use the doorbell part to, for instance, trigger flows.

Regards,
Bas

**Comment by hunter707** [comment]
Thanks Bas, I'm gonna try it this weekend.

Groetjes,
Loek
