### ISSUE TITLE
Some devices in the list do not have correct typenumber

### ISSUE THREAD

**Issue by rhannink** [athombv/nl.klikaanklikuit#9]
Hello,

When I add a new KAKU device, I can sleet the correct KAU device from a list. Most icons in the list have the correct type number, some devices (e.g. the new AYCT-202) are listed as device instead of a type number.

Gr. Remco

![zones___devices_-_homey](https://cloud.githubusercontent.com/assets/1661824/22145600/5dd75e66-df02-11e6-8de5-8fe708af7113.png)

----------addition-------------
I saw on slack that the type number is actually behind devices. but I am not able to scale the Homey app on my Mac. Maybe you can just leave the devices. part away????

**Comment by BasKiers** [comment]
Hi,

I assume you got this issue when you installed the app from github where not all translations were added. Could you confirm that the current version in the app store does display the model number correctly?

Regards,
Bas
